/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e3e2e0",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#e9c176",
        "on-tertiary-fixed": "#1a1c1a",
        "surface-container": "#efeded",
        "on-surface": "#1b1c1c",
        "on-secondary-fixed": "#1c1b1b",
        "surface-bright": "#fbf9f9",
        "inverse-on-surface": "#f2f0f0",
        "on-secondary-container": "#636262",
        "surface-container-low": "#f5f3f3",
        "on-primary-fixed-variant": "#5d4201",
        "on-background": "#1b1c1c",
        "outline": "#7f7667",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e9e8e7",
        "on-primary": "#ffffff",
        "tertiary": "#5e5f5d",
        "surface": "#fbf9f9",
        "on-error": "#ffffff",
        "outline-variant": "#d1c5b4",
        "surface-variant": "#e4e2e2",
        "on-primary-container": "#4e3700",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#775a19",
        "on-secondary-fixed-variant": "#474746",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#303031",
        "background": "#fbf9f9",
        "on-tertiary-container": "#3a3b39",
        "tertiary-fixed-dim": "#c7c6c4",
        "secondary-container": "#e2dfde",
        "surface-dim": "#dbdad9",
        "surface-container-highest": "#e4e2e2",
        "on-surface-variant": "#4e4639",
        "on-tertiary-fixed-variant": "#464745",
        "on-primary-fixed": "#261900",
        "error": "#ba1a1a",
        "primary": {
          DEFAULT: "#775a19",
          hover: "#5d4201",
        },
        "secondary": "#5f5e5e",
        "inverse-primary": "#e9c176",
        "secondary-fixed": "#e5e2e1",
        "tertiary-container": "#a5a5a3",
        "primary-container": "#c5a059",
        "primary-fixed": "#ffdea5",
        "primary-orig": {
          DEFAULT: '#c99b6d',
          hover: '#b48557',
        },
        "secondary-orig": '#1a1a1a',
        "accent-orig": '#f4ece4',
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "section-gap-mobile": "64px",
        "section-gap-desktop": "120px",
        "gutter": "24px",
        "container-max-width": "1280px",
        "base": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-sm": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "sans": ['Inter', 'sans-serif'],
        "serif": ['Playfair Display', 'serif'],
      },
      fontSize: {
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "500"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "56px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
